spring.application.name=prueba
management.endpoints.web.exposure.include=health,info

management.info.env.enabled=true
info.app.name=registros-service
info.app.description=Microservicio de prueba para registros
info.app.version=1.0.1
management.info.java.enabled=true
management.info.os.enabled=true

spring.jpa.show-sql=true